# .github/workflows/news-monitor.yml
name: China Policy News Monitor

permissions:
  contents: write
  actions: read

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  monitor-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests
        
    - name: Run news monitor
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python news_monitor.py
        
    - name: Commit processed articles file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Update processed articles [skip ci]'
        file_pattern: 'processed_articles.json'
        commit_user_name: 'GitHub Action'
        commit_user_email: 'action@github.com'
