# .github/workflows/news-monitor.yml
name: AI-Enhanced China Policy News Monitor

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil
        
    - name: Run AI-enhanced news monitor
      env:
        # Email settings
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        
        # AI API Keys (add these to your repository secrets)
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
        
        # Optional: If you want to run Ollama locally (advanced users)
        # OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      run: |
        python news_monitor.py
